title: Aishat Sadiq
#logo: #add relative path after creating images folder
description: Activist-Scholar, in that order
show_downloads: False
theme: jekyll-theme-tactile

# Bio: Psychology doctoral candidate with special interest in data science for social policy
