title: Aishat Sadiq
#logo: #add relative path after creating images folder
show_downloads: False
remote_theme: pages-themes/tactile@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

